services:
  postgres:
    image: postgres:13
    container_name: postgres_host
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rss_parser
      POSTGRES_PORT: 5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "5000:5000"
    working_dir: /app
    env_file:
      - .env.example
